# Use a Node.js base image
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY .. ./
RUN npm run build

# --- Production Stage ---
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist/
COPY --from=builder /app/node_modules ./node_modules/
COPY package*.json ./
EXPOSE 3000
CMD ["dist/bin/genieacs-nbi"]
